### PR TITLE
add files for TRTS

### PR DESCRIPTION
**Pull request by dlightdlight**

### CODE REVIEW

**Comment by SquarshPie** [comment]
BDTRL5KLOC5SGYIETYCJIG5Y2JESAVNZVZ6S3N4QN44ZOG5U2IPQ

**Comment by SquarshPie** [comment]
KDCYAOPASXIQNDAD4TJBASBBRMBNTF65HXFJUA6QKJVVJU53L3YQ

**Comment by dlightdlight** [comment]
KKVXPK4MPRTWEMHNZ4AVQA3VWXCWKCA3GXMGAGYYUC2OHLABNNLQ

**Review by SquarshPie — COMMENTED** [review]
TRTS logo looks great!

**Pull request merged**
