### PR TITLE
MAGMA-445362421

### PR DESCRIPTION
**Pull request by floatbeta**
Adding $MAGM icon.

### CODE REVIEW

**Comment by floatbeta** [comment]
Added Icon

**Comment by floatbeta** [comment]
Is there anything wrong with the logos?

**Comment by ertekinno** [comment]
Icon.svg and icon.png should show the same icon. Unfortunately, icon.svg in this commit is broken. Please update your icon.svg and make sure it's consistent with the PNG version.

**Comment by floatbeta** [comment]
Okay. We will get that fixed.

**Pull request closed without merging**
