### PR TITLE
VYBE-558978094 for review

### PR DESCRIPTION
**Pull request by belmarjohnperido**

### CODE REVIEW

**Comment by ipaleka** [comment]
> Note that these icons will mostly be used in rounded areas. Elements located at the corners of the container may not be visible in some applications.

icon
icon

**Comment by ertekinno** [comment]
Can you confirm which one is correct? If the version in the comment is final, if you close this PR and open a new PR, I can merge it.

**Comment by belmarjohnperido** [comment]
@ertekinno [1c3a213](https://github.com/tinymanorg/asa-list/pull/581/commits/1c3a213f3a4e0f3cc822d76f94415846f324b2d4) this one might work thank you!

**Comment by belmarjohnperido** [comment]
> > Note that these icons will mostly be used in rounded areas. Elements located at the corners of the container may not be visible in some applications.
> 
> icon icon
> 
> [Source](https://dashboard.vybecrypto.com/static/media/VybeWhiteRed.d0070ca2ff4843e33c4d.png)

@ipaleka we will be using this. Thanks for the help! :-)

**Comment by belmarjohnperido** [comment]
@ipaleka I think the latest comment on this PR is now final. Thank you!

**Comment by ertekinno** [comment]
Awesome! I merged the final version. Thanks @ipaleka

**Pull request merged**
