### PR TITLE
Create Add Logo - SeedBomb - 523605642

### PR DESCRIPTION
**Pull request by SeedBombAngus**
Seed Bomb Transparent (1)

### CODE REVIEW

**Comment by SeedBombAngus** [comment]
Hi TM Team, 

Hope you are all well and having a good weekend! I was hoping that you may be able to add this Logo to the SeedBomb ASA on Tinyman. My name is Angus and I am one of the committee members there. You can see that the logo aligns with our website (seed-bomb.com) and our social media handles (links at base of the webpages). 

All the best,
Angus

**Comment by ertekinno** [comment]
Please read the guidelines and rules before creating a pull request. This commit is not suitable to the repository.

There should be a folder named with unit_name-asset_id, e.g. "USDC-31566704" without adding any space. And icon.png and icon.svg should be in this folder.

**Comment by SeedBombAngus** [comment]
Apologies, I messed this one up! Let me get a proper Pull Request in today in compliance with the guidelines. Thank you very much for your help. All the best, AngusSeedBomb ASA Limited On Mon, 31 Jan 2022 at 10:43 am ertekinno wrote:
Please read the guidelines and rules before creating a pull request. This commit is not suitable to the repository.
There should be a folder named with unit_name-asset_id, e.g. "USDC-31566704" without adding any space. And icon.png and icon.svg should be in this folder.

—Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.
You are receiving this because you authored the thread.Message ID: ***@***.***>
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/tinymanorg/asa-list/pull/260#issuecomment-1025601941",
"url": "https://github.com/tinymanorg/asa-list/pull/260#issuecomment-1025601941",
"name": "View Pull Request"
},
"description": "View this Pull Request on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by SeedBombAngus** [comment]
Hi, Please can you let us know if that resubmission is suitable? I followers instructions but am less familiar with Git, so may have messed up! Sorry if so. Many thanks,AngusSeedBomb ASA Limited On Mon, 31 Jan 2022 at 10:46 am Me wrote:Apologies, I messed this one up! Let me get a proper Pull Request in today in compliance with the guidelines. Thank you very much for your help. All the best, AngusSeedBomb ASA Limited On Mon, 31 Jan 2022 at 10:43 am ertekinno wrote:
Please read the guidelines and rules before creating a pull request. This commit is not suitable to the repository.
There should be a folder named with unit_name-asset_id, e.g. "USDC-31566704" without adding any space. And icon.png and icon.svg should be in this folder.

—Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.
You are receiving this because you authored the thread.Message ID: ***@***.***>
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/tinymanorg/asa-list/pull/260#issuecomment-1025601941",
"url": "https://github.com/tinymanorg/asa-list/pull/260#issuecomment-1025601941",
"name": "View Pull Request"
},
"description": "View this Pull Request on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Pull request closed without merging**
