### PR TITLE
Adding JOY-561127431

### PR DESCRIPTION
**Pull request by cryptowhim**
icon
icon

### CODE REVIEW

**Comment by ertekinno** [comment]
Hey, thanks for sending request, but this PR is not suitable to merge. Both icons should have their own file. While JOY-561127431 has the folder, other icon doesn't have. Please update your pull request. You can view all the requirements from [README.md](https://github.com/tinymanorg/asa-list/tree/main#readme).

**Comment by cryptowhim** [comment]
Okay thank you

**Comment by cryptowhim** [comment]
So does that mean JOY is okay?
Apologies, I do read, but its a bit new.

Many thanks
Jan

**Comment by cryptowhim** [comment]
I created a folder named appropriately. In that folder are the png and the
SVg named with icon.png and icon.svg.
I just reread the readme file.

I thought I did the right thing, so I am unsure where to go now?

**Pull request closed without merging**
