### PR TITLE
CAIN-1115850955

### PR DESCRIPTION
**Pull request by PulchritudinousChattel**
icon png
icon svg

### CODE REVIEW

**Comment by PulchritudinousChattel** [comment]
Request to add icon to ASA icon repository for visibility at Vestige.fi

**Comment by PulchritudinousChattel** [comment]
Verification of pull request/ "CAIN-1115850955" creator wallet ownership:

Transaction ID: BXCZN2GEOTVL2B24PEM4MJ5C2RBCODUTWJF334JO4NYH7DIZYUJQ

**Comment by ertekinno** [comment]
Hello, thanks for sending icons. Unfortunately, this commit is not suitable to the repository.

- First, you should create a folder. There should be a folder named with `unit_name-asset_id`, e.g. "USDC-31566704" without adding any space. And icon files should be in this folder.
- Icon names should be `icon.png` and `icon.svg`

Please update your commit according to this feedback. You can also view all the requirements from [README.md](https://github.com/tinymanorg/asa-list/tree/main#readme) before creating a pull request.

**Comment by PulchritudinousChattel** [comment]
Hey thanks for the information. HEre is the updated pull request! I followed your instructions - please let me know that I've done it correctly this time. Uploading a folder is impossible here so I've created it as a .zip file. Thank you :)
[CAIN-1115850955.zip](https://github.com/tinymanorg/asa-list/files/11893237/CAIN-1115850955.zip)

**Comment by PulchritudinousChattel** [comment]
I've updated the pull request now in a message reply with the folder
containing icons as a .zip file. Please confirm whether this is correct and
the process can now be completed? Thanks!!

**Pull request closed without merging**
