### PR TITLE
ORDINALS-1116319755

### PR DESCRIPTION
**Pull request by COLLAPSEDWORLDS**
https://vestige.fi/asset/1116319755

### CODE REVIEW

**Comment by COLLAPSEDWORDLS** [comment]
Creator wallet zero transaction : IWO4H6UDVETVB5LKAJPDAPOBJY36PR5VTWCHUHUF2HRPQ5QG26WQ

Please tell me in comment, if anything is wrong with the upload file

**Comment by COLLAPSEDWORLDS** [comment]
icon.svg

icon

**Comment by COLLAPSEDWORLDS** [comment]
I had to change my icon.svg because the first version was pixelated and not vectorised! Can you take this new file into account? Thanks

**Review by COLLAPSEDWORLDS — COMMENTED** [review]
icon

**Pull request closed without merging**
